// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAMEmTvXk8W_c1r5C3VE7czYMSQWC_heo',
    appId: '1:571975210880:web:597079a333191c5d355365',
    messagingSenderId: '571975210880',
    projectId: 'splash-131020',
    authDomain: 'splash-131020.firebaseapp.com',
    storageBucket: 'splash-131020.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJ9GmRHLN-kx31PTWY-LEfI6SlCDZVUE',
    appId: '1:571975210880:android:35ec0d2aac25f970355365',
    messagingSenderId: '571975210880',
    projectId: 'splash-131020',
    storageBucket: 'splash-131020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_sadzdoTOrCKkisQB6iz-17BPY4iFB0',
    appId: '1:571975210880:ios:90df73ffd52f03ca355365',
    messagingSenderId: '571975210880',
    projectId: 'splash-131020',
    storageBucket: 'splash-131020.appspot.com',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi_sadzdoTOrCKkisQB6iz-17BPY4iFB0',
    appId: '1:571975210880:ios:90df73ffd52f03ca355365',
    messagingSenderId: '571975210880',
    projectId: 'splash-131020',
    storageBucket: 'splash-131020.appspot.com',
    iosBundleId: 'com.example.course',
  );
}
